steps:
  # Fetch cache archive
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: '/bin/bash'
    args:
      [
        '-c',
        'gcloud storage cp gs://${_CACHE_BUCKET_NAME}/caches/caf-web/cache.tar.gz . || exit 0',
      ]

  # Unzip cache
  - name: bash
    args: ['-c', 'tar xzf cache.tar.gz || exit 0']

  # Install deps
  - name: node:lts-alpine
    id: 'yarn-install'
    entrypoint: yarn
    args: ['install', '--frozen-lockfile']

  # Build app
  - name: node:lts-alpine
    entrypoint: yarn
    args: ['build']
    env:
      - 'NEXT_PUBLIC_HOST_URL=https://gendai-art.org'
      - 'NEXT_PUBLIC_BASE_PATH=/caf/inada'
      - 'NEXT_GTAG_TRACKING_ID=G-RL974H0D69'

  # Clear public storage if objects are exists
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: '/bin/bash'
    args:
      ['-c', 'gcloud storage rm -a gs://${_PUBLIC_BUCKET_NAME}/** || exit 0']

  # Upload to public storage
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: 'gcloud'
    args: ['storage', 'cp', '-r', './out/*', 'gs://${_PUBLIC_BUCKET_NAME}/']

  # Set max-age of HTML files (others lives 3600s by default of GCS)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: 'gsutil'
    args:
      [
        'setmeta',
        '-h',
        'cache-control: public, max-age=60',
        'gs://${_PUBLIC_BUCKET_NAME}/**/*.html',
      ]

  # Zip node_modules and .next
  - name: bash
    id: 'archive cache'
    args: ['tar', 'czf', 'cache.tar.gz', 'node_modules', '.next']
    waitFor: ['yarn-install']

  # Cache archive
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: 'gcloud'
    waitFor: ['archive cache']
    args:
      [
        'storage',
        'cp',
        'cache.tar.gz',
        'gs://${_CACHE_BUCKET_NAME}/caches/caf-web/',
      ]

substitutions:
  _PUBLIC_BUCKET_NAME: caf-ushio-web
  _CACHE_BUCKET_NAME: ushio-tide_cloudbuild
